<?php

use Illuminate\Database\Seeder;

class BooksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //DBファサードを使ってデータを入れる
        \DB::table('books')->insert([
            [
                'id' => '1',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => '痛快!コンピュータ学',
                'image_file_name' => 'image_01',
                'publisher' => '集英社文庫',
                'release_date' => '2002/03/20',
                'price' => '1773',
                'content' => 'コンピュータへの興味の原点',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '2',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'コンピュータはなぜ動くのか',
                'image_file_name' => 'image_02',
                'publisher' => '日経BP社',
                'release_date' => '2003/06/02',
                'price' => '2640',
                'content' => 'コンピュータに対しての知識が少なく、あまり内容が結びつかなかった記憶があります',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '3',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル3',
                'image_file_name' => 'image_01',
                'publisher' => '集英社文庫',
                'release_date' => '2002/03/20',
                'price' => '1773',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '4',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル4',
                'image_file_name' => 'image_02',
                'publisher' => '日経BP社',
                'release_date' => '2003/06/02',
                'price' => '2640',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '5',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル5',
                'image_file_name' => 'image_01',
                'publisher' => '集英社文庫',
                'release_date' => '2002/03/20',
                'price' => '1773',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '6',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル6',
                'image_file_name' => 'image_02',
                'publisher' => '日経BP社',
                'release_date' => '2003/06/02',
                'price' => '2640',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '7',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル7',
                'image_file_name' => 'image_01',
                'publisher' => '集英社文庫',
                'release_date' => '2002/03/20',
                'price' => '1773',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '8',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル8',
                'image_file_name' => 'image_02',
                'publisher' => '日経BP社',
                'release_date' => '2003/06/02',
                'price' => '2640',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '9',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル9',
                'image_file_name' => 'image_01',
                'publisher' => '集英社文庫',
                'release_date' => '2002/03/20',
                'price' => '1773',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '10',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル10',
                'image_file_name' => 'image_02',
                'publisher' => '日経BP社',
                'release_date' => '2003/06/02',
                'price' => '2640',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '11',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル11',
                'image_file_name' => 'image_01',
                'publisher' => '集英社文庫',
                'release_date' => '2002/03/20',
                'price' => '1773',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '12',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル12',
                'image_file_name' => 'image_02',
                'publisher' => '日経BP社',
                'release_date' => '2003/06/02',
                'price' => '2640',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '13',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル13',
                'image_file_name' => 'image_01',
                'publisher' => '集英社文庫',
                'release_date' => '2002/03/20',
                'price' => '1773',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '14',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル14',
                'image_file_name' => 'image_02',
                'publisher' => '日経BP社',
                'release_date' => '2003/06/02',
                'price' => '2640',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '15',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル15',
                'image_file_name' => 'image_01',
                'publisher' => '集英社文庫',
                'release_date' => '2002/03/20',
                'price' => '1773',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '16',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル16',
                'image_file_name' => 'image_02',
                'publisher' => '日経BP社',
                'release_date' => '2003/06/02',
                'price' => '2640',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '17',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル17',
                'image_file_name' => 'image_01',
                'publisher' => '集英社文庫',
                'release_date' => '2002/03/20',
                'price' => '1773',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '18',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル18',
                'image_file_name' => 'image_02',
                'publisher' => '日経BP社',
                'release_date' => '2003/06/02',
                'price' => '2640',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '19',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル19',
                'image_file_name' => 'image_01',
                'publisher' => '集英社文庫',
                'release_date' => '2002/03/20',
                'price' => '1773',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '20',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル20',
                'image_file_name' => 'image_02',
                'publisher' => '日経BP社',
                'release_date' => '2003/06/02',
                'price' => '2640',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => '21',
                'bookshelf_id' => '1',
                'category_id' => '1',
                'evaluation_id' => '3',
                'name' => 'サンプル21',
                'image_file_name' => 'image_02',
                'publisher' => '日経BP社',
                'release_date' => '2003/06/02',
                'price' => '2640',
                'content' => 'サンプルデータサンプルデータサンプルデータサンプルデータサンプルデータ',
                'is_published' => '1',
                'is_deleted' => '0',
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
